const prayCard = {
  image: [
    { file: "prayCard/image/player/whole.webp", name: "whole" },
    { file: "prayCard/image/player/laugh.webp", name: "laugh" },
    { file: "prayCard/image/player/normal.webp", name: "normal" },
    { file: "prayCard/image/player/scarface.webp", name: "scarface" },
    { file: "prayCard/image/player/shock.webp", name: "shock" },
    { file: "prayCard/image/player/smile.webp", name: "smile" },
    { file: "prayCard/image/player/stunned.webp", name: "stunned" },
    { file: "prayCard/image/player/talk.webp", name: "talk" },
    { file: "prayCard/image/player/think.webp", name: "think" },
    { file: "prayCard/image/horsegril/angry.webp", name: "angry" },
    { file: "prayCard/image/horsegril/evil.webp", name: "evil" },
    { file: "prayCard/image/horsegril/happy.webp", name: "happy" },
    { file: "prayCard/image/horsegril/normal.webp", name: "normal" },
    { file: "prayCard/image/horsegril/smile.webp", name: "smile" },
    { file: "prayCard/image/horsegril/talk.webp", name: "talk" },
    { file: "prayCard/image/horsegril/think.webp", name: "think" },
    { file: "prayCard/image/taskimg/citycoffee.webp", name: "citycoffee" },
    { file: "prayCard/image/taskimg/citynightsky.webp", name: "citynightsky" },
    { file: "prayCard/image/taskimg/firstmeet.webp", name: "firstmeet" },
    { file: "prayCard/image/taskimg/fiveyen.webp", name: "fiveyen" },
    { file: "prayCard/image/taskimg/flyinghorse.webp", name: "flyinghorse" },
    { file: "prayCard/image/taskimg/heroicspirit.webp", name: "heroicspirit" },
    { file: "prayCard/image/taskimg/horizobse.webp", name: "horizobse" },
    { file: "prayCard/image/taskimg/horsegirl.webp", name: "horsegirl" },
    { file: "prayCard/image/taskimg/kid.webp", name: "kid" },
    { file: "prayCard/image/taskimg/leavepark.webp", name: "leavepark" },
    { file: "prayCard/image/taskimg/lumcard.webp", name: "lumcard" },
    { file: "prayCard/image/taskimg/maze.webp", name: "maze" },
    { file: "prayCard/image/taskimg/observe.webp", name: "observe" },
    { file: "prayCard/image/taskimg/park.webp", name: "park" },
    { file: "prayCard/image/taskimg/rock.webp", name: "rock" },
    { file: "prayCard/image/taskimg/sayname.webp", name: "sayname" },
    { file: "prayCard/image/taskimg/scan.webp", name: "scan" },
    { file: "prayCard/image/taskimg/shrine.webp", name: "shrine" },
    { file: "prayCard/image/taskimg/shrineisland.webp", name: "shrineisland" },
    { file: "prayCard/image/taskimg/stonecard.webp", name: "stonecard" },
    { file: "prayCard/image/taskimg/stonelian.webp", name: "stonelian" },
    { file: "prayCard/image/taskimg/stonewlian.webp", name: "stonewlian" },
    { file: "prayCard/image/taskimg/taoyuanshrine.webp", name: "taoyuanshrine" },
    { file: "prayCard/image/taskimg/toriiorig.webp", name: "toriiorig" },
    { file: "prayCard/image/taskimg/wish.webp", name: "wish" },
    { file: "prayCard/image/taskimg/worshiphall.webp", name: "worshiphall" },
    { file: "prayCard/image/storyback/citynight.webp", name: "citynight" },
    { file: "prayCard/image/storyback/coverbackgrount.webp", name: "coverbackgrount" },
    { file: "prayCard/image/storyback/damagedtorii.webp", name: "damagedtorii" },
    { file: "prayCard/image/storyback/darkmountainroad.webp", name: "darkmountainroad" },
    { file: "prayCard/image/storyback/holyarea.webp", name: "holyarea" },
    { file: "prayCard/image/storyback/park.webp", name: "park" },
    { file: "prayCard/image/storyback/stonedog.webp", name: "stonedog" },
    { file: "prayCard/image/storyback/torii.webp", name: "torii" },
    { file: "prayCard/image/storyback/worshiphall.webp", name: "worshiphall" },
    { file: "prayCard/image/evtboj/starrysky.webp", name: "starrysky" },
    { file: "prayCard/image/evtback/citynight.webp", name: "citynight" },
    { file: "prayCard/image/evtback/darkmountainroad.webp", name: "darkmountainroad" },
    { file: "prayCard/image/evtback/park.webp", name: "park" },
    { file: "prayCard/image/evtback/stonedog.webp", name: "stonedog" },
    { file: "prayCard/image/evtback/stonelantern.webp", name: "stonelantern" },
    { file: "prayCard/image/evtback/torii.webp", name: "torii" },
    { file: "prayCard/image/evtback/worshiphall.webp", name: "worshiphall" },
    { file: "prayCard/image/arimg/dog.webp", name: "dog" },
    { file: "prayCard/image/arimg/fate.webp", name: "fate" },
    { file: "prayCard/image/arimg/horse.webp", name: "horse" },
    { file: "prayCard/image/arimg/name.webp", name: "name" },
    { file: "prayCard/image/arimg/qdog.webp", name: "qdog" },
    { file: "prayCard/image/arimg/starlink.webp", name: "starlink" },
    { file: "prayCard/image/arimg/stonelantern.webp", name: "stonelantern" },
    { file: "prayCard/image/arimg/torii.webp", name: "torii" },
    { file: "prayCard/image/arimg/toriiclue.webp", name: "toriiclue" },
  ],
  armark: [
    { file: "prayCard/armark/badge.mind", name: "badge" },
    { file: "prayCard/armark/dog.mind", name: "dog" },
    { file: "prayCard/armark/horse.mind", name: "horse" },
    { file: "prayCard/armark/stonelantern.mind", name: "stonelantern" },
    { file: "prayCard/armark/torii.mind", name: "torii" },
    { file: "prayCard/armark/worship.mind", name: "worship" },
  ],
  armodel: [],
  music: [],
  video: [],
};

window.setprayCard = () => {
  return prayCard;
};
