const loveStory = {
  image: [
    { file: "loveStory/image/evtbg/livingroom_1.webp", name: "livingroom_1" },
    { file: "loveStory/image/evtbg/livingroom_2.webp", name: "livingroom_2" },
    { file: "loveStory/image/evtbg/meeting.webp", name: "meeting" },
    { file: "loveStory/image/evtbg/runaway.webp", name: "runaway" },
    { file: "loveStory/image/evtbg/speech.webp", name: "speech" },
    { file: "loveStory/image/evtbg/evtbg00.webp", name: "evtbg00" },
    { file: "loveStory/image/evtbg/evtbg02.webp", name: "evtbg02" },
    { file: "loveStory/image/evtbg/evtbg03.webp", name: "evtbg03" },
    { file: "loveStory/image/evtbg/evtbg04.webp", name: "evtbg04" },
    { file: "loveStory/image/evtbg/evtbg05.webp", name: "evtbg05" },
    { file: "loveStory/image/evtbg/evtbg06.webp", name: "evtbg06" },
    { file: "loveStory/image/evtbg/evtbg07.webp", name: "evtbg07" },
    { file: "loveStory/image/evtbg/evtbg08.webp", name: "evtbg08" },
    { file: "loveStory/image/evtbg/evtbg09.webp", name: "evtbg09" },
    { file: "loveStory/image/evtbg/evtbg10.webp", name: "evtbg10" },
    { file: "loveStory/image/evtbg/evtbg11.webp", name: "evtbg11" },
    { file: "loveStory/image/evtbg/evtbg12.webp", name: "evtbg12" },
    { file: "loveStory/image/evtbg/evtbg13.webp", name: "evtbg13" },
    { file: "loveStory/image/evtbg/evtbg14.webp", name: "evtbg14" },
    { file: "loveStory/image/evtbg/evtbg15.webp", name: "evtbg15" },
    { file: "loveStory/image/evtbg/evtbg16.webp", name: "evtbg16" },
    { file: "loveStory/image/evtbg/evtbg17.webp", name: "evtbg17" },
    { file: "loveStory/image/evtbg/evtbg18.webp", name: "evtbg18" },
    { file: "loveStory/image/evtbg/evtbg19.webp", name: "evtbg19" },
    { file: "loveStory/image/evtbg/evtbg20.webp", name: "evtbg20" },
    { file: "loveStory/image/evtbg/evtbg21.webp", name: "evtbg21" },
    { file: "loveStory/image/evtbg/evtbg22.webp", name: "evtbg22" },
    { file: "loveStory/image/evtbg/evtbg23.webp", name: "evtbg23" },
    { file: "loveStory/image/evtbg/evtbg24.webp", name: "evtbg24" },
    { file: "loveStory/image/evtbg/evtbg25.webp", name: "evtbg25" },
    { file: "loveStory/image/evtbg/evtbg26.webp", name: "evtbg26" },
    { file: "loveStory/image/evtbg/evtbg27.webp", name: "evtbg27" },
    { file: "loveStory/image/evtbg/evtbg28.webp", name: "evtbg28" },
    { file: "loveStory/image/evtbg/evtbg29.webp", name: "evtbg29" },
    { file: "loveStory/image/evtbg/evtbg30.webp", name: "evtbg30" },
    { file: "loveStory/image/evtbg/evtbg31.webp", name: "evtbg31" },
    { file: "loveStory/image/evtbg/evtbg32.webp", name: "evtbg32" },
    { file: "loveStory/image/evtbg/evtbg33.webp", name: "evtbg33" },

    { file: "loveStory/image/role/hero.webp", name: "hero" },
    { file: "loveStory/image/role/heroine.webp", name: "heroine" },
    { file: "loveStory/image/role/guard.webp", name: "guard" },

    { file: "loveStory/image/taskimg/wedding.webp", name: "wedding" },
    { file: "loveStory/image/taskimg/boy.webp", name: "boy" },
    { file: "loveStory/image/taskimg/girl.webp", name: "girl" },
    { file: "loveStory/image/taskimg/task01.webp", name: "task01" },
    { file: "loveStory/image/taskimg/task02.webp", name: "task02" },
    { file: "loveStory/image/taskimg/task03.webp", name: "task03" },
    { file: "loveStory/image/taskimg/task04.webp", name: "task04" },
    { file: "loveStory/image/taskimg/task05.webp", name: "task05" },
    { file: "loveStory/image/taskimg/task06.webp", name: "task06" },
    { file: "loveStory/image/taskimg/task07.webp", name: "task07" },
    { file: "loveStory/image/taskimg/task08.webp", name: "task08" },
    { file: "loveStory/image/taskimg/task09.webp", name: "task09" },

    { file: "loveStory/image/taskimg/end01.webp", name: "end01" },
    { file: "loveStory/image/taskimg/end02.webp", name: "end02" },
    { file: "loveStory/image/taskimg/end03.webp", name: "end03" },

    { file: "loveStory/image/itembg/itembg.webp", name: "itembg" },
    { file: "loveStory/image/itembg/itembg02.webp", name: "itembg02" },
    { file: "loveStory/image/itembg/itembg03.webp", name: "itembg03" },
    { file: "loveStory/image/itembg/itembg04.webp", name: "itembg04" },
    { file: "loveStory/image/itembg/itembg05.webp", name: "itembg05" },
    { file: "loveStory/image/itembg/itembg06.webp", name: "itembg06" },
    { file: "loveStory/image/itembg/itembg07.webp", name: "itembg07" },
    { file: "loveStory/image/itembg/itembg08.webp", name: "itembg08" },

    { file: "loveStory/image/objImg/obj01.webp", name: "obj01" },
    { file: "loveStory/image/objImg/obj02.webp", name: "obj02" },
    { file: "loveStory/image/objImg/obj03.webp", name: "obj03" },
    { file: "loveStory/image/objImg/obj04.webp", name: "obj04" },
    { file: "loveStory/image/objImg/obj05.webp", name: "obj05" },
    { file: "loveStory/image/objImg/obj06.webp", name: "obj06" },

    { file: "loveStory/image/panorama/panorama01.webp", name: "panorama01" },

    { file: "loveStory/image/arimg/arview.webp", name: "arview" },
    { file: "loveStory/image/arimg/catar.webp", name: "catar" },
    { file: "loveStory/image/arimg/cat1.webp", name: "cat1" },
    { file: "loveStory/image/arimg/cat2.webp", name: "cat2" },
    { file: "loveStory/image/arimg/cat3.webp", name: "cat3" },
    { file: "loveStory/image/arimg/cat4.webp", name: "cat4" },
    { file: "loveStory/image/arimg/cat5.webp", name: "cat5" },
    { file: "loveStory/image/arimg/cat6.webp", name: "cat6" },
    { file: "loveStory/image/arimg/cat7.webp", name: "cat7" },
  ],
  armark: [
    { file: "loveStory/armark/targets.mind", name: "targets" },
    { file: "loveStory/armark/cat.mind", name: "cat" },
  ],
  armodel: [],
  music: [],
  video: [],
};

window.setloveStory = () => {
  return loveStory;
};
