const kasugayama = {
  image: [
    // 角色
    { file: "kasugayama/image/role/player.webp", name: "player" },
    { file: "kasugayama/image/role/mirror.webp", name: "mirror" },
    { file: "kasugayama/image/role/crow.webp", name: "crow" },
    { file: "kasugayama/image/role/dog.webp", name: "dog" },
    { file: "kasugayama/image/role/frog.webp", name: "frog" },
    { file: "kasugayama/image/role/horse.webp", name: "horse" },
    { file: "kasugayama/image/role/empty.webp", name: "empty" },
    { file: "kasugayama/image/role/leadrole.webp", name: "leadrole" },

    // 任務
    { file: "kasugayama/image/taskimg/task_1.webp", name: "task_1" },
    { file: "kasugayama/image/taskimg/task_2.webp", name: "task_2" },
    { file: "kasugayama/image/taskimg/task_3.webp", name: "task_3" },
    { file: "kasugayama/image/taskimg/task_4.webp", name: "task_4" },
    { file: "kasugayama/image/taskimg/task_5.webp", name: "task_5" },
    { file: "kasugayama/image/taskimg/task_6.webp", name: "task_6" },
    { file: "kasugayama/image/taskimg/task_7.webp", name: "task_7" },
    { file: "kasugayama/image/taskimg/task_8.webp", name: "task_8" },
    { file: "kasugayama/image/taskimg/task_9.webp", name: "task_9" },
    { file: "kasugayama/image/taskimg/task_10.webp", name: "task_10" },
    { file: "kasugayama/image/taskimg/task_11.webp", name: "task_11" },
    { file: "kasugayama/image/taskimg/task_12.webp", name: "task_12" },
    { file: "kasugayama/image/taskimg/task_13.webp", name: "task_13" },
    { file: "kasugayama/image/taskimg/task_14.webp", name: "task_14" },
    { file: "kasugayama/image/taskimg/task_15.webp", name: "task_15" },
    { file: "kasugayama/image/taskimg/task_16.webp", name: "task_16" },
    { file: "kasugayama/image/taskimg/task_17.webp", name: "task_17" },
    { file: "kasugayama/image/taskimg/task_18.webp", name: "task_18" },
    { file: "kasugayama/image/taskimg/task_19.webp", name: "task_19" },
    { file: "kasugayama/image/taskimg/task_20.webp", name: "task_20" },
    { file: "kasugayama/image/taskimg/task_21.webp", name: "task_21" },
    { file: "kasugayama/image/taskimg/task_22.webp", name: "task_22" },
    { file: "kasugayama/image/taskimg/task_23.webp", name: "task_23" },
    { file: "kasugayama/image/taskimg/task_24.webp", name: "task_24" },
    { file: "kasugayama/image/taskimg/task_25.webp", name: "task_25" },
    { file: "kasugayama/image/taskimg/task_26.webp", name: "task_26" },
    { file: "kasugayama/image/taskimg/task_27.webp", name: "task_27" },
    { file: "kasugayama/image/taskimg/task_28.webp", name: "task_28" },
    { file: "kasugayama/image/taskimg/task_29.webp", name: "task_29" },
    { file: "kasugayama/image/taskimg/transform1.webp", name: "transform1" },
    { file: "kasugayama/image/taskimg/transform2.webp", name: "transform2" },
    { file: "kasugayama/image/taskimg/transform3.webp", name: "transform3" },

    // 物件
    { file: "kasugayama/image/objimg/objimg_1.webp", name: "objimg_1" },
    { file: "kasugayama/image/objimg/objimg_2.webp", name: "objimg_2" },
    { file: "kasugayama/image/objimg/objimg_3.webp", name: "objimg_3" },
    { file: "kasugayama/image/objimg/objimg_4.webp", name: "objimg_4" },
    { file: "kasugayama/image/objimg/objimg_5.webp", name: "objimg_5" },
    { file: "kasugayama/image/objimg/objimg_6.webp", name: "objimg_6" },
    { file: "kasugayama/image/objimg/objimg_7.webp", name: "objimg_7" },

    // 事件項目
    { file: "kasugayama/image/itembg/itembg_1.webp", name: "itembg_1" },
    { file: "kasugayama/image/itembg/itembg_2.webp", name: "itembg_2" },
    { file: "kasugayama/image/itembg/itembg_3.webp", name: "itembg_3" },
    { file: "kasugayama/image/itembg/itembg_4.webp", name: "itembg_4" },
    { file: "kasugayama/image/itembg/itembg_5.webp", name: "itembg_5" },
    { file: "kasugayama/image/itembg/itembg_6.webp", name: "itembg_6" },
    { file: "kasugayama/image/itembg/itembg_7.webp", name: "itembg_7" },
    { file: "kasugayama/image/itembg/itembg_8.webp", name: "itembg_8" },
    { file: "kasugayama/image/itembg/itembg_9.webp", name: "itembg_9" },
    { file: "kasugayama/image/itembg/itembg_10.webp", name: "itembg_10" },
    { file: "kasugayama/image/itembg/itembg_11.webp", name: "itembg_11" },
    { file: "kasugayama/image/itembg/itembg_12.webp", name: "itembg_12" },

    // 事件背景
    { file: "kasugayama/image/evtbg/evtbg_1.webp", name: "evtbg_1" },
    { file: "kasugayama/image/evtbg/evtbg_2.webp", name: "evtbg_2" },
    { file: "kasugayama/image/evtbg/evtbg_3.webp", name: "evtbg_3" },
    { file: "kasugayama/image/evtbg/evtbg_4.webp", name: "evtbg_4" },
    { file: "kasugayama/image/evtbg/evtbg_5.webp", name: "evtbg_5" },
    { file: "kasugayama/image/evtbg/evtbg_6.webp", name: "evtbg_6" },
    { file: "kasugayama/image/evtbg/evtbg_7.webp", name: "evtbg_7" },
    { file: "kasugayama/image/evtbg/evtbg_8.webp", name: "evtbg_8" },
    { file: "kasugayama/image/evtbg/evtbg_9.webp", name: "evtbg_9" },
    { file: "kasugayama/image/evtbg/evtbg_10.webp", name: "evtbg_10" },
    { file: "kasugayama/image/evtbg/evtbg_11.webp", name: "evtbg_11" },
    { file: "kasugayama/image/evtbg/entrypointbg.webp", name: "entrypointbg" },
  ],
  armark: [],
  armodel: [],
  music: [],
  video: [],
};

window.setkasugayama = () => {
  return kasugayama;
};
