const bearinfested = {
  image: [
    { file: "bearinfested/image/role/role01.webp", name: "role01" },
    { file: "bearinfested/image/role/role02.webp", name: "role02" },
    { file: "bearinfested/image/role/role03.webp", name: "role03" },
    { file: "bearinfested/image/role/role04.webp", name: "role04" },
    { file: "bearinfested/image/role/role05.webp", name: "role05" },
    { file: "bearinfested/image/role/role06.webp", name: "role06" },
    { file: "bearinfested/image/role/role07.webp", name: "role07" },
    { file: "bearinfested/image/role/role08.webp", name: "role08" },
    { file: "bearinfested/image/role/role09.webp", name: "role09" },
    { file: "bearinfested/image/role/role10.webp", name: "role10" },
    { file: "bearinfested/image/role/role11.webp", name: "role11" },
    { file: "bearinfested/image/role/role12.webp", name: "role12" },
    { file: "bearinfested/image/role/role13.webp", name: "role13" },
    { file: "bearinfested/image/role/role14.webp", name: "role14" },
    { file: "bearinfested/image/role/role15.webp", name: "role15" },
    { file: "bearinfested/image/role/role16.webp", name: "role16" },
    { file: "bearinfested/image/role/role17.webp", name: "role17" },
    { file: "bearinfested/image/role/role18.webp", name: "role18" },
    { file: "bearinfested/image/role/irole01.webp", name: "irole01" },
    { file: "bearinfested/image/role/irole02.webp", name: "irole02" },
    { file: "bearinfested/image/role/irole03.webp", name: "irole03" },
    { file: "bearinfested/image/role/irole04.webp", name: "irole04" },
    { file: "bearinfested/image/role/irole05.webp", name: "irole05" },
    { file: "bearinfested/image/role/irole06.webp", name: "irole06" },
    { file: "bearinfested/image/role/irole07.webp", name: "irole07" },
    { file: "bearinfested/image/role/irole08.webp", name: "irole08" },
    { file: "bearinfested/image/role/irole09.webp", name: "irole09" },
    { file: "bearinfested/image/role/irole10.webp", name: "irole10" },
    { file: "bearinfested/image/role/irole11.webp", name: "irole11" },
    { file: "bearinfested/image/role/srole01.webp", name: "srole01" },
    { file: "bearinfested/image/evtbg/bg01.webp", name: "bg01" },
    { file: "bearinfested/image/evtbg/bg02.webp", name: "bg02" },
    { file: "bearinfested/image/evtbg/bg03.webp", name: "bg03" },
    { file: "bearinfested/image/evtbg/bg04.webp", name: "bg04" },
    { file: "bearinfested/image/evtbg/bg05.webp", name: "bg05" },
    { file: "bearinfested/image/evtbg/bg06.webp", name: "bg06" },
    { file: "bearinfested/image/evtbg/bg07.webp", name: "bg07" },
    { file: "bearinfested/image/evtbg/bg08.webp", name: "bg08" },
    { file: "bearinfested/image/evtbg/bg09.webp", name: "bg09" },
    { file: "bearinfested/image/evtbg/bg10.webp", name: "bg10" },
    { file: "bearinfested/image/evtbg/bg11.webp", name: "bg11" },
    { file: "bearinfested/image/evtbg/bg12.webp", name: "bg12" },
    { file: "bearinfested/image/evtbg/bg13.webp", name: "bg13" },
    { file: "bearinfested/image/evtbg/bg14.webp", name: "bg14" },
    { file: "bearinfested/image/evtbg/bg15.webp", name: "bg15" },
    { file: "bearinfested/image/evtbg/bg16.webp", name: "bg16" },
    { file: "bearinfested/image/evtbg/bg17.webp", name: "bg17" },
    { file: "bearinfested/image/evtbg/bg18.webp", name: "bg18" },
    { file: "bearinfested/image/evtbg/bg19.webp", name: "bg19" },
    { file: "bearinfested/image/taskimg/coastaltown.webp", name: "coastaltown" },
    { file: "bearinfested/image/objimg/subway.webp", name: "subway" },
    { file: "bearinfested/image/objimg/buddha.webp", name: "buddha" },
    { file: "bearinfested/image/objimg/light.webp", name: "light" },
    { file: "bearinfested/image/objimg/azimuthclock.webp", name: "azimuthclock" },
    { file: "bearinfested/image/objimg/starrysky.webp", name: "starrysky" },
    { file: "bearinfested/image/objimg/incantation.webp", name: "incantation" },
    { file: "bearinfested/image/arimg/imperialseal00.webp", name: "imperialseal00" },
    { file: "bearinfested/image/arimg/imperialseal01.webp", name: "imperialseal01" },
    { file: "bearinfested/image/arimg/imperialseal02.webp", name: "imperialseal02" },
    { file: "bearinfested/image/arimg/imperialseal03.webp", name: "imperialseal03" },
    { file: "bearinfested/image/arimg/imperialseal04.webp", name: "imperialseal04" },
    { file: "bearinfested/image/arimg/deepshrine.webp", name: "deepshrine" },
  ],
  armark: [
    { file: "bearinfested/armark/zhuyin.mind", name: "zhuyin" },
    { file: "bearinfested/armark/sun.mind", name: "sun" },
  ],
  armodel: [],
  music: [],
  video: [],
};

window.setBearinfested = () => {
  return bearinfested;
};
