const bearinfested = {
  image: [
    { file: "bearinfested/image/role/role01.webp", name: "role01" },
    { file: "bearinfested/image/role/role02.webp", name: "role02" },
    { file: "bearinfested/image/role/role03.webp", name: "role03" },
    { file: "bearinfested/image/role/role04.webp", name: "role04" },
    { file: "bearinfested/image/role/role05.webp", name: "role05" },
    { file: "bearinfested/image/role/role06.webp", name: "role06" },
    { file: "bearinfested/image/role/role07.webp", name: "role07" },
    { file: "bearinfested/image/role/role08.webp", name: "role08" },
    { file: "bearinfested/image/role/role09.webp", name: "role09" },
    { file: "bearinfested/image/role/role10.webp", name: "role10" },
    { file: "bearinfested/image/role/role11.webp", name: "role11" },
    { file: "bearinfested/image/role/role12.webp", name: "role12" },
    { file: "bearinfested/image/role/role13.webp", name: "role13" },
    { file: "bearinfested/image/role/role14.webp", name: "role14" },
    { file: "bearinfested/image/role/role15.webp", name: "role15" },
    { file: "bearinfested/image/role/role16.webp", name: "role16" },
    { file: "bearinfested/image/role/role17.webp", name: "role17" },
    { file: "bearinfested/image/role/role18.webp", name: "role18" },
    { file: "bearinfested/image/role/irole01.webp", name: "irole01" },
    { file: "bearinfested/image/role/irole02.webp", name: "irole02" },
    { file: "bearinfested/image/role/irole03.webp", name: "irole03" },
    { file: "bearinfested/image/role/irole04.webp", name: "irole04" },
    { file: "bearinfested/image/role/irole05.webp", name: "irole05" },
    { file: "bearinfested/image/role/irole06.webp", name: "irole06" },
    { file: "bearinfested/image/role/irole07.webp", name: "irole07" },
    { file: "bearinfested/image/role/irole08.webp", name: "irole08" },
    { file: "bearinfested/image/role/irole09.webp", name: "irole09" },
    { file: "bearinfested/image/role/irole10.webp", name: "irole10" },
    { file: "bearinfested/image/role/irole11.webp", name: "irole11" },
    { file: "bearinfested/image/role/srole01.webp", name: "srole01" },
    { file: "bearinfested/image/role/view01.webp", name: "view01" },
    { file: "bearinfested/image/role/view02.webp", name: "view02" },
    { file: "bearinfested/image/role/view03.webp", name: "view03" },
    { file: "bearinfested/image/role/view04.webp", name: "view04" },
    { file: "bearinfested/image/role/view05.webp", name: "view05" },
    { file: "bearinfested/image/role/doorman.webp", name: "doorman" },
    { file: "bearinfested/image/role/mirror.webp", name: "mirror" },
    { file: "bearinfested/image/role/runemrror.webp", name: "runemrror" },
    { file: "bearinfested/image/evtbg/bg00.webp", name: "bg00" },
    { file: "bearinfested/image/evtbg/bg01.webp", name: "bg01" },
    { file: "bearinfested/image/evtbg/bg02.webp", name: "bg02" },
    { file: "bearinfested/image/evtbg/bg03.webp", name: "bg03" },
    { file: "bearinfested/image/evtbg/bg04.webp", name: "bg04" },
    { file: "bearinfested/image/evtbg/bg05.webp", name: "bg05" },
    { file: "bearinfested/image/evtbg/bg06.webp", name: "bg06" },
    { file: "bearinfested/image/evtbg/bg07.webp", name: "bg07" },
    { file: "bearinfested/image/evtbg/bg08.webp", name: "bg08" },
    { file: "bearinfested/image/evtbg/bg09.webp", name: "bg09" },
    { file: "bearinfested/image/evtbg/bg10.webp", name: "bg10" },
    { file: "bearinfested/image/evtbg/bg11.webp", name: "bg11" },
    { file: "bearinfested/image/evtbg/bg12.webp", name: "bg12" },
    { file: "bearinfested/image/evtbg/bg13.webp", name: "bg13" },
    { file: "bearinfested/image/evtbg/bg14.webp", name: "bg14" },
    { file: "bearinfested/image/evtbg/bg15.webp", name: "bg15" },
    { file: "bearinfested/image/evtbg/bg16.webp", name: "bg16" },
    { file: "bearinfested/image/evtbg/bg17.webp", name: "bg17" },
    { file: "bearinfested/image/evtbg/bg18.webp", name: "bg18" },
    { file: "bearinfested/image/evtbg/bg19.webp", name: "bg19" },
    { file: "bearinfested/image/evtbg/bg20.webp", name: "bg20" },
    { file: "bearinfested/image/evtbg/bg21.webp", name: "bg21" },
    { file: "bearinfested/image/evtbg/bg22.webp", name: "bg22" },
    { file: "bearinfested/image/evtbg/bg23.webp", name: "bg23" },
    { file: "bearinfested/image/evtbg/bg24.webp", name: "bg24" },
    { file: "bearinfested/image/evtbg/bg25.webp", name: "bg25" },
    { file: "bearinfested/image/evtbg/bg26.webp", name: "bg26" },
    { file: "bearinfested/image/evtbg/bg27.webp", name: "bg27" },
    { file: "bearinfested/image/evtbg/bg28.webp", name: "bg28" },
    { file: "bearinfested/image/evtbg/bg29.webp", name: "bg29" },
    { file: "bearinfested/image/evtbg/bg30.webp", name: "bg30" },
    { file: "bearinfested/image/evtbg/bg31.webp", name: "bg31" },
    { file: "bearinfested/image/evtbg/bg32.webp", name: "bg32" },
    { file: "bearinfested/image/evtbg/bg33.webp", name: "bg33" },

    { file: "bearinfested/image/taskimg/task01.webp", name: "task01" },
    { file: "bearinfested/image/taskimg/task02.webp", name: "task02" },
    { file: "bearinfested/image/taskimg/task03.webp", name: "task03" },
    { file: "bearinfested/image/taskimg/task04.webp", name: "task04" },
    { file: "bearinfested/image/taskimg/task05.webp", name: "task05" },
    { file: "bearinfested/image/taskimg/task06.webp", name: "task06" },
    { file: "bearinfested/image/taskimg/task07.webp", name: "task07" },
    { file: "bearinfested/image/taskimg/task08.webp", name: "task08" },
    { file: "bearinfested/image/taskimg/task09.webp", name: "task09" },
    { file: "bearinfested/image/taskimg/task10.webp", name: "task10" },
    { file: "bearinfested/image/taskimg/task11.webp", name: "task11" },
    { file: "bearinfested/image/taskimg/task12.webp", name: "task12" },
    { file: "bearinfested/image/taskimg/task13.webp", name: "task13" },
    { file: "bearinfested/image/taskimg/task14.webp", name: "task14" },
    { file: "bearinfested/image/taskimg/task15.webp", name: "task15" },
    { file: "bearinfested/image/taskimg/task16.webp", name: "task16" },
    { file: "bearinfested/image/taskimg/task17.webp", name: "task17" },
    { file: "bearinfested/image/taskimg/task18.webp", name: "task18" },
    { file: "bearinfested/image/taskimg/task19.webp", name: "task19" },
    { file: "bearinfested/image/taskimg/task20.webp", name: "task20" },
    { file: "bearinfested/image/taskimg/task21.webp", name: "task21" },
    { file: "bearinfested/image/objimg/subway.webp", name: "subway" },
    { file: "bearinfested/image/objimg/buddha.webp", name: "buddha" },
    { file: "bearinfested/image/objimg/light.webp", name: "light" },
    { file: "bearinfested/image/objimg/azimuthclock.webp", name: "azimuthclock" },
    { file: "bearinfested/image/objimg/starrysky.webp", name: "starrysky" },
    { file: "bearinfested/image/objimg/incantation.webp", name: "incantation" },
    { file: "bearinfested/image/objprops/props01.webp", name: "props01" },
    { file: "bearinfested/image/objprops/props02.webp", name: "props02" },
    { file: "bearinfested/image/objprops/props03.webp", name: "props03" },
    { file: "bearinfested/image/objprops/props04.webp", name: "props04" },
    { file: "bearinfested/image/arimg/imperialseal00.webp", name: "imperialseal00" },
    { file: "bearinfested/image/arimg/imperialseal01.webp", name: "imperialseal01" },
    { file: "bearinfested/image/arimg/imperialseal02.webp", name: "imperialseal02" },
    { file: "bearinfested/image/arimg/imperialseal03.webp", name: "imperialseal03" },
    { file: "bearinfested/image/arimg/imperialseal04.webp", name: "imperialseal04" },
    { file: "bearinfested/image/arimg/deepshrine.webp", name: "deepshrine" },
    { file: "bearinfested/image/arimg/platycodon.webp", name: "platycodon" },
    { file: "bearinfested/image/itembg/itembg01.webp", name: "itembg01" },

    { file: "bearinfested/image/guidelines/guidelines01.webp", name: "guidelines01" },
    { file: "bearinfested/image/guidelines/guidelines02.webp", name: "guidelines02" },
    { file: "bearinfested/image/guidelines/guidelines03.webp", name: "guidelines03" },
    { file: "bearinfested/image/guidelines/guidelines04.webp", name: "guidelines04" },
    { file: "bearinfested/image/guidelines/guidelines05.webp", name: "guidelines05" },
    { file: "bearinfested/image/guidelines/guidelines06.webp", name: "guidelines06" },
    { file: "bearinfested/image/guidelines/guidelines07.webp", name: "guidelines07" },
    { file: "bearinfested/image/guidelines/guidelines08.webp", name: "guidelines08" },
    { file: "bearinfested/image/guidelines/guidelines09.webp", name: "guidelines09" },
    { file: "bearinfested/image/guidelines/guidelines10.webp", name: "guidelines10" },
  ],
  armark: [
    { file: "bearinfested/armark/zhuyin.mind", name: "zhuyin" },
    { file: "bearinfested/armark/sun.mind", name: "sun" },
    { file: "bearinfested/armark/platycodon.mind", name: "platycodon" },
  ],
  armodel: [],
  music: [],
  video: [],
};

window.setBearinfested = () => {
  return bearinfested;
};
