const nazotabi = {
  image: [
    { file: "nazotabi/image/task/task01.webp", name: "task01" },
    { file: "nazotabi/image/task/task02.webp", name: "task02" },
    { file: "nazotabi/image/task/task03.webp", name: "task03" },
    { file: "nazotabi/image/task/task04.webp", name: "task04" },
    { file: "nazotabi/image/task/task05.webp", name: "task05" },
    { file: "nazotabi/image/task/task06.webp", name: "task06" },
    { file: "nazotabi/image/task/task07.webp", name: "task07" },
    { file: "nazotabi/image/task/task08.webp", name: "task08" },
    { file: "nazotabi/image/task/task09.webp", name: "task09" },
    { file: "nazotabi/image/task/task10.webp", name: "task10" },
    { file: "nazotabi/image/task/task11.webp", name: "task11" },
    { file: "nazotabi/image/task/task12.webp", name: "task12" },
    { file: "nazotabi/image/task/task13.webp", name: "task13" },
    { file: "nazotabi/image/task/task14.webp", name: "task14" },

    { file: "nazotabi/image/role/bear01.webp", name: "bear01" },
    { file: "nazotabi/image/role/bear02.webp", name: "bear02" },
    { file: "nazotabi/image/role/bear03.webp", name: "bear03" },
    { file: "nazotabi/image/role/bear04.webp", name: "bear04" },
    { file: "nazotabi/image/role/bear05.webp", name: "bear05" },
    { file: "nazotabi/image/role/bear06.webp", name: "bear06" },
    { file: "nazotabi/image/role/bear07.webp", name: "bear07" },
    { file: "nazotabi/image/role/bear08.webp", name: "bear08" },
    { file: "nazotabi/image/role/bear09.webp", name: "bear09" },
    { file: "nazotabi/image/role/bear10.webp", name: "bear10" },
    { file: "nazotabi/image/role/bear11.webp", name: "bear11" },
    { file: "nazotabi/image/role/bear12.webp", name: "bear12" },
    { file: "nazotabi/image/role/bear13.webp", name: "bear13" },
    { file: "nazotabi/image/role/bear14.webp", name: "bear14" },
    { file: "nazotabi/image/role/bear15.webp", name: "bear15" },
    { file: "nazotabi/image/role/bear16.webp", name: "bear16" },
    { file: "nazotabi/image/role/bear17.webp", name: "bear17" },

    { file: "nazotabi/image/role/miko01.webp", name: "miko01" },
    { file: "nazotabi/image/role/miko02.webp", name: "miko02" },
    { file: "nazotabi/image/role/miko03.webp", name: "miko03" },
    { file: "nazotabi/image/role/miko04.webp", name: "miko04" },
    { file: "nazotabi/image/role/miko05.webp", name: "miko05" },
    { file: "nazotabi/image/role/miko06.webp", name: "miko06" },
    { file: "nazotabi/image/role/miko07.webp", name: "miko07" },
    { file: "nazotabi/image/role/miko08.webp", name: "miko08" },
    { file: "nazotabi/image/role/miko09.webp", name: "miko09" },

    { file: "nazotabi/image/role/amaterasu01.webp", name: "amaterasu01" },
    { file: "nazotabi/image/role/amaterasu02.webp", name: "amaterasu02" },
    { file: "nazotabi/image/role/amaterasu03.webp", name: "amaterasu03" },
    { file: "nazotabi/image/role/amaterasu04.webp", name: "amaterasu04" },
    { file: "nazotabi/image/role/amaterasu05.webp", name: "amaterasu05" },
    { file: "nazotabi/image/role/amaterasu06.webp", name: "amaterasu06" },
  ],
  armark: [],
  armodel: [],
  music: [
    { file: "nazotabi/music/one.MP3", name: "one" },
    { file: "nazotabi/music/two.MP3", name: "two" },
  ],
  video: [],
};

window.setnazotabi = () => {
  return nazotabi;
};
